apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: k8stestapi
  name: k8stestapi
  namespace: k8stestapi
spec:
  repicas: 1
  strategy: 
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  selector:
    matchLabels:
      app: k8stestapi
  replicas: 1
  template:
    metadata:
      labels:
        app: k8stestapi
        type: backend
    spec:
      containers:
        - name: k8stestapi
          image: cotters07/k8stestapi
          imagePullPolicy: Always
          ports:
            - containerPort: 5001